icon: search
label: fabianmichael.meta.tab.label

columns:
  meta_main:
    width: 2/3
    fields:
      meta_global_general: fields/meta/global-general-group
      meta_global_schema: fields/meta/global-schema-group
      meta_global_ogengraph: fields/meta/global-opengraph-group
      meta_global_twitter: fields/meta/global-twitter-group
      meta_global_robots: fields/meta/global-robots-group

  meta_sidebar:
    sticky: true
    width: 1/3
    sections:
      meta_files: sections/meta/files
